# Generated by Django 2.1 on 2018-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(blank=True, upload_to='car_image'),
        ),
    ]
